server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/transfer
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    root: INFO

token:
  expiration-time: 3600000
  secret: myVerySuperDuperSecretKey123456789 # needs to be saved in secure place
