server:
  port: ${SERVER_PORT:8080}

spring:
  config:
    activate:
      on-profile: docker
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://pixel-postgres:5432/transfer}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
